/**
 * API requests are built from and responses are based on:
 * https://app.swaggerhub.com/apis-docs/WeatherAPI.com/WeatherAPI/1.0.2#/APIs/history-weather
 */

export namespace TestHelperOutboundIntegrationHandlerWeatherApi {
  export const urlPayloadMap: Record<string, unknown> = {
    "https://api.weatherapi.com/v1/history.json?key=TEST&q=Mersin&aqi=no&dt=2025-04-16":
      {
        location: {
          name: "Mersin",
          region: "Mersin",
          country: "Turkey",
          lat: 36.7328,
          lon: 34.6442,
          tz_id: "Europe/Istanbul",
          localtime_epoch: 1744877705,
          localtime: "2025-04-17 11:15",
        },
        forecast: {
          forecastday: [
            {
              date: "2025-04-16",
              date_epoch: 1744761600,
              day: {
                maxtemp_c: 18.9,
                maxtemp_f: 66,
                mintemp_c: 8.4,
                mintemp_f: 47.1,
                avgtemp_c: 13.4,
                avgtemp_f: 56.2,
                maxwind_mph: 7.4,
                maxwind_kph: 11.9,
                totalprecip_mm: 0,
                totalprecip_in: 0,
                totalsnow_cm: 0,
                avgvis_km: 10,
                avgvis_miles: 6,
                avghumidity: 56,
                daily_will_it_rain: 0,
                daily_chance_of_rain: 0,
                daily_will_it_snow: 0,
                daily_chance_of_snow: 0,
                condition: {
                  text: "Sunny",
                  icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                  code: 1000,
                },
                uv: 5,
              },
              astro: {
                sunrise: "06:06 AM",
                sunset: "07:17 PM",
                moonrise: "10:53 PM",
                moonset: "07:32 AM",
                moon_phase: "Waning Gibbous",
                moon_illumination: 93,
              },
            },
          ],
        },
      },

    "https://api.weatherapi.com/v1/history.json?key=TEST&q=Mersin&aqi=no&dt=2025-04-14":
      {
        location: {
          name: "Mersin",
          region: "Mersin",
          country: "Turkey",
          lat: 36.7328,
          lon: 34.6442,
          tz_id: "Europe/Istanbul",
          localtime_epoch: 1744877798,
          localtime: "2025-04-17 11:16",
        },
        forecast: {
          forecastday: [
            {
              date: "2025-04-14",
              date_epoch: 1744588800,
              day: {
                maxtemp_c: 16.1,
                maxtemp_f: 60.9,
                mintemp_c: 6.8,
                mintemp_f: 44.3,
                avgtemp_c: 11.8,
                avgtemp_f: 53.2,
                maxwind_mph: 8.9,
                maxwind_kph: 14.4,
                totalprecip_mm: 0.9,
                totalprecip_in: 0.04,
                totalsnow_cm: 0,
                avgvis_km: 9.9,
                avgvis_miles: 6,
                avghumidity: 44,
                daily_will_it_rain: 1,
                daily_chance_of_rain: 100,
                daily_will_it_snow: 0,
                daily_chance_of_snow: 0,
                condition: {
                  text: "Patchy rain possible",
                  icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
                  code: 1063,
                },
                uv: 4,
              },
              astro: {
                sunrise: "06:09 AM",
                sunset: "07:15 PM",
                moonrise: "08:51 PM",
                moonset: "06:31 AM",
                moon_phase: "Waning Gibbous",
                moon_illumination: 99,
              },
            },
          ],
        },
      },

    "https://api.weatherapi.com/v1/history.json?key=TEST&q=Mersin&aqi=no&dt=2025-04-13&end_dt=2025-04-16":
      {
        location: {
          name: "Mersin",
          region: "Mersin",
          country: "Turkey",
          lat: 36.7328,
          lon: 34.6442,
          tz_id: "Europe/Istanbul",
          localtime_epoch: 1744877962,
          localtime: "2025-04-17 11:19",
        },
        forecast: {
          forecastday: [
            {
              date: "2025-04-13",
              date_epoch: 1744502400,
              day: {
                maxtemp_c: 17.4,
                maxtemp_f: 63.4,
                mintemp_c: 7.2,
                mintemp_f: 45,
                avgtemp_c: 11.7,
                avgtemp_f: 53,
                maxwind_mph: 6.9,
                maxwind_kph: 11.2,
                totalprecip_mm: 0,
                totalprecip_in: 0,
                totalsnow_cm: 0,
                avgvis_km: 10,
                avgvis_miles: 6,
                avghumidity: 55,
                daily_will_it_rain: 0,
                daily_chance_of_rain: 0,
                daily_will_it_snow: 0,
                daily_chance_of_snow: 0,
                condition: {
                  text: "Overcast",
                  icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
                  code: 1009,
                },
                uv: 4,
              },
              astro: {
                sunrise: "06:10 AM",
                sunset: "07:14 PM",
                moonrise: "07:52 PM",
                moonset: "06:06 AM",
                moon_phase: "Full Moon",
                moon_illumination: 100,
              },
            },
            {
              date: "2025-04-14",
              date_epoch: 1744588800,
              day: {
                maxtemp_c: 16.1,
                maxtemp_f: 60.9,
                mintemp_c: 6.8,
                mintemp_f: 44.3,
                avgtemp_c: 11.8,
                avgtemp_f: 53.2,
                maxwind_mph: 8.9,
                maxwind_kph: 14.4,
                totalprecip_mm: 0.9,
                totalprecip_in: 0.04,
                totalsnow_cm: 0,
                avgvis_km: 9.9,
                avgvis_miles: 6,
                avghumidity: 44,
                daily_will_it_rain: 1,
                daily_chance_of_rain: 100,
                daily_will_it_snow: 0,
                daily_chance_of_snow: 0,
                condition: {
                  text: "Patchy rain possible",
                  icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
                  code: 1063,
                },
                uv: 4,
              },
              astro: {
                sunrise: "06:09 AM",
                sunset: "07:15 PM",
                moonrise: "08:51 PM",
                moonset: "06:31 AM",
                moon_phase: "Waning Gibbous",
                moon_illumination: 99,
              },
            },
            {
              date: "2025-04-15",
              date_epoch: 1744675200,
              day: {
                maxtemp_c: 18.6,
                maxtemp_f: 65.5,
                mintemp_c: 8.3,
                mintemp_f: 46.9,
                avgtemp_c: 13.4,
                avgtemp_f: 56.1,
                maxwind_mph: 9.8,
                maxwind_kph: 15.8,
                totalprecip_mm: 0,
                totalprecip_in: 0,
                totalsnow_cm: 0,
                avgvis_km: 10,
                avgvis_miles: 6,
                avghumidity: 43,
                daily_will_it_rain: 0,
                daily_chance_of_rain: 0,
                daily_will_it_snow: 0,
                daily_chance_of_snow: 0,
                condition: {
                  text: "Sunny",
                  icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                  code: 1000,
                },
                uv: 5,
              },
              astro: {
                sunrise: "06:07 AM",
                sunset: "07:16 PM",
                moonrise: "09:53 PM",
                moonset: "06:59 AM",
                moon_phase: "Waning Gibbous",
                moon_illumination: 97,
              },
            },
            {
              date: "2025-04-16",
              date_epoch: 1744761600,
              day: {
                maxtemp_c: 18.9,
                maxtemp_f: 66,
                mintemp_c: 8.4,
                mintemp_f: 47.1,
                avgtemp_c: 13.4,
                avgtemp_f: 56.2,
                maxwind_mph: 7.4,
                maxwind_kph: 11.9,
                totalprecip_mm: 0,
                totalprecip_in: 0,
                totalsnow_cm: 0,
                avgvis_km: 10,
                avgvis_miles: 6,
                avghumidity: 56,
                daily_will_it_rain: 0,
                daily_chance_of_rain: 0,
                daily_will_it_snow: 0,
                daily_chance_of_snow: 0,
                condition: {
                  text: "Sunny",
                  icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                  code: 1000,
                },
                uv: 5,
              },
              astro: {
                sunrise: "06:06 AM",
                sunset: "07:17 PM",
                moonrise: "10:53 PM",
                moonset: "07:32 AM",
                moon_phase: "Waning Gibbous",
                moon_illumination: 93,
              },
            },
          ],
        },
      },

    "https://api.weatherapi.com/v1/current.json?key=TEST&q=Mersin&aqi=no": {
      location: {
        name: "Mersin",
        region: "Mersin",
        country: "Turkey",
        lat: 36.7328,
        lon: 34.6442,
        tz_id: "Europe/Istanbul",
        localtime_epoch: 1754566325,
        localtime: "2025-08-07 14:32",
      },
      current: {
        last_updated_epoch: 1754566200,
        last_updated: "2025-08-07 14:30",
        temp_c: 29.2,
        temp_f: 84.5,
        is_day: 1,
        condition: {
          text: "Partly Cloudy",
          icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
          code: 1003,
        },
        wind_mph: 8.5,
        wind_kph: 13.7,
        wind_degree: 161,
        wind_dir: "SSE",
        pressure_mb: 1006.0,
        pressure_in: 29.69,
        precip_mm: 0.0,
        precip_in: 0.0,
        humidity: 71,
        cloud: 26,
        feelslike_c: 33.4,
        feelslike_f: 92.1,
        windchill_c: 29.2,
        windchill_f: 84.5,
        heatindex_c: 33.4,
        heatindex_f: 92.1,
        dewpoint_c: 23.4,
        dewpoint_f: 74.2,
        vis_km: 10.0,
        vis_miles: 6.0,
        uv: 8.1,
        gust_mph: 9.8,
        gust_kph: 15.8,
      },
    },
  };
}
