
export const LOCAL_STORAGE_KEY_DARK_THEME = "DARK_THEME";
export const LOCAL_STORAGE_KEY_LANGUAGE = "LANGUAGE";
export const LOCAL_STORAGE_KEY_REPORT_SECTIONS = "REPORT_SECTIONS";
export const LOCAL_STORAGE_KEY_REPORT_SECTIONS_PREFILL = "REPORT_SECTIONS_PREFILL";
