services:
  postgres:
    image: "timescale/timescaledb:latest-pg18"
    restart: always
    environment:
      POSTGRES_DB: eoms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  back:
    image: ${VAR_IMAGE_NAME_BACK}:${VAR_IMAGE_TAG}
    restart: always
    pull_policy: always
    depends_on:
      - postgres
    environment:
      PORT: "3000"
      ENV_NAME: $VAR_ENV_NAME
      BUILD_TIME: $VAR_BUILD_TIME
      BUILD_ID: $VAR_BUILD_ID

      DB_MIG_DIR: $VAR_DB_MIG_DIR
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: eoms
      DB_RESET_EACH_RUN: "true"

      AMQP_HOST: $VAR_AMQP_HOST
      AMQP_PORT: "$VAR_AMQP_PORT"
      AMQP_USER: $VAR_AMQP_USER
      AMQP_PASSWORD: $VAR_AMQP_PASSWORD

      QUEUE_REPORT_RENDER: $VAR_QUEUE_REPORT_RENDER
      QUEUE_REPORT_PDF: $VAR_QUEUE_REPORT_PDF
      QUEUE_ANALYZER_FEATURE_ELIMINATION: $VAR_QUEUE_ANALYZER_FEATURE_ELIMINATION
      QUEUE_ANALYZER_FEATURE_ELIMINATION_RESULT: $VAR_QUEUE_ANALYZER_FEATURE_ELIMINATION_RESULT

      STORAGE_DISK_PATH: ./storage_data

      COOKIE_SECRET: DUMMY

      ISSUE_REPORT_MATRIX_HOST: $VAR_ISSUE_REPORT_MATRIX_HOST
      ISSUE_REPORT_MATRIX_ROOM_ID: $VAR_ISSUE_REPORT_MATRIX_ROOM_ID
      ISSUE_REPORT_MATRIX_ACCESS_TOKEN: $VAR_ISSUE_REPORT_MATRIX_ACCESS_TOKEN

      TOLGEE_API_URL: $VAR_TOLGEE_API_URL
      TOLGEE_API_KEY: $VAR_TOLGEE_API_KEY
      TOLGEE_PROJECT_ID: $VAR_TOLGEE_PROJECT_ID

      OTEL_TRACE_EXPORT_URL: $VAR_OTEL_TRACE_EXPORT_URL
      LOG_LOKI_ENDPOINT: $VAR_LOG_LOKI_ENDPOINT
      WEATHER_API_TOKEN: "$VAR_WEATHER_API_TOKEN"
      OPEN_WEATHER_API_TOKEN: "$VAR_OPEN_WEATHER_TOKEN"
      WORKSPACE_ROOT_DOMAINS: $VAR_WORKSPACE_ROOT_DOMAINS

  front:
    image: ${VAR_IMAGE_NAME_FRONT}:${VAR_IMAGE_TAG}
    restart: always
    pull_policy: always
    labels:
      - homer=${VAR_HOMER}
    ports:
      - "${VAR_DEPLOY_PORT}:80"
