services:
  back:
    image: ${VAR_IMAGE_NAME_BACK}:${VAR_IMAGE_TAG}
    restart: always
    pull_policy: always
    environment:
      PORT: "3000"
      ENV_NAME: $VAR_ENV_NAME
      BUILD_TIME: $VAR_BUILD_TIME
      BUILD_ID: $VAR_BUILD_ID

      DB_MIG_DIR: $VAR_DB_MIG_DIR
      DB_HOST: $VAR_POSTGRES_HOST
      DB_PORT: "$VAR_POSTGRES_PORT"
      DB_USER: postgres
      DB_PASSWORD: $VAR_POSTGRES_PASSWORD
      DB_NAME: $VAR_POSTGRES_DB_NAME

      STORAGE_S3_ACCESS_KEY_ID: $VAR_STORAGE_S3_ACCESS_KEY_ID
      STORAGE_S3_REGION: $VAR_STORAGE_S3_REGION
      STORAGE_S3_BUCKET: $VAR_STORAGE_S3_BUCKET
      STORAGE_S3_ENDPOINT: $VAR_STORAGE_S3_ENDPOINT
      STORAGE_S3_SECRET_ACCESS_KEY: $VAR_STORAGE_S3_SECRET_ACCESS_KEY

      AMQP_HOST: $VAR_AMQP_HOST
      AMQP_PORT: "$VAR_AMQP_PORT"
      AMQP_USER: $VAR_AMQP_USER
      AMQP_PASSWORD: $VAR_AMQP_PASSWORD

      QUEUE_AGENT_READINGS: $VAR_QUEUE_AGENT_READINGS
      QUEUE_AGENT_STATS: $VAR_QUEUE_AGENT_STATS
      QUEUE_REPORT_RENDER: $VAR_QUEUE_REPORT_RENDER
      QUEUE_REPORT_PDF: $VAR_QUEUE_REPORT_PDF
      QUEUE_ANALYZER_FEATURE_ELIMINATION: $VAR_QUEUE_ANALYZER_FEATURE_ELIMINATION
      QUEUE_ANALYZER_FEATURE_ELIMINATION_RESULT: $VAR_QUEUE_ANALYZER_FEATURE_ELIMINATION_RESULT

      PRIVATE_INTEGRATION_PROXY_URL: $VAR_PRIVATE_INTEGRATION_PROXY_URL
      PRIVATE_INTEGRATION_PROXY_USER: $VAR_PRIVATE_INTEGRATION_PROXY_USER
      PRIVATE_INTEGRATION_PROXY_PASSWORD: $VAR_PRIVATE_INTEGRATION_PROXY_PASSWORD

      ISSUE_REPORT_MATRIX_HOST: $VAR_ISSUE_REPORT_MATRIX_HOST
      ISSUE_REPORT_MATRIX_ROOM_ID: $VAR_ISSUE_REPORT_MATRIX_ROOM_ID
      ISSUE_REPORT_MATRIX_ACCESS_TOKEN: $VAR_ISSUE_REPORT_MATRIX_ACCESS_TOKEN

      SECURE_COOKIE: true
      COOKIE_SECRET: $VAR_COOKIE_SECRET
      HCAPTCHA_SECRET_KEY: $VAR_HCAPTCHA_SECRET_KEY
      WORKSPACE_ROOT_DOMAINS: $VAR_WORKSPACE_ROOT_DOMAINS

      OTEL_TRACE_EXPORT_URL: $VAR_OTEL_TRACE_EXPORT_URL
      LOG_LOKI_ENDPOINT: $VAR_LOG_LOKI_ENDPOINT
      WEATHER_API_TOKEN: $VAR_WEATHER_API_TOKEN
      OPEN_WEATHER_API_TOKEN: $VAR_OPEN_WEATHER_TOKEN

  front:
    restart: always
    pull_policy: always
    image: ${VAR_IMAGE_NAME_FRONT}:${VAR_IMAGE_TAG}
    ports:
      - "${VAR_DEPLOY_PORT}:80"
