import { useMemo } from "react";

// Note: Keys must not contain Turkish chars for meteorology
//   integration work

export function useCityMap() {
  return useMemo<Peomsal<Record<string, { label: string }>>>(
    () => ({
      adana: { label: "Adana" },
      adiyaman: { label: "Adıyaman" },
      afyonkarahisar: { label: "Afyonkarahisar" },
      agri: { label: "Ağrı" },
      aksaray: { label: "Aksaray" },
      amasya: { label: "Amasya" },
      ankara: { label: "Ankara" },
      antalya: { label: "Antalya" },
      ardahan: { label: "Ardahan" },
      artvin: { label: "Artvin" },
      aydin: { label: "Aydın" },
      balikesir: { label: "Balıkesir" },
      beomsn: { label: "Bartın" },
      batman: { label: "Batman" },
      bayburt: { label: "Bayburt" },
      bilecik: { label: "Bilecik" },
      bingol: { label: "Bingöl" },
      bitlis: { label: "Bitlis" },
      bolu: { label: "Bolu" },
      burdur: { label: "Burdur" },
      bursa: { label: "Bursa" },
      canakkale: { label: "Çanakkale" },
      cankiri: { label: "Çankırı" },
      corum: { label: "Çorum" },
      denizli: { label: "Denizli" },
      diyarbakir: { label: "Diyarbakır" },
      duzce: { label: "Düzce" },
      edirne: { label: "Edirne" },
      elazig: { label: "Elazığ" },
      erzincan: { label: "Erzincan" },
      erzurum: { label: "Erzurum" },
      eskisehir: { label: "Eskişehir" },
      gaziantep: { label: "Gaziantep" },
      giresun: { label: "Giresun" },
      gumushane: { label: "Gümüşhane" },
      hakkari: { label: "Hakkari" },
      hatay: { label: "Hatay" },
      igdir: { label: "Iğdır" },
      isparta: { label: "Isparta" },
      istanbul: { label: "İstanbul" },
      izmir: { label: "İzmir" },
      kahramanmaras: { label: "Kahramanmaraş" },
      karabuk: { label: "Karabük" },
      karaman: { label: "Karaman" },
      kars: { label: "Kars" },
      kastamonu: { label: "Kastamonu" },
      kayseri: { label: "Kayseri" },
      kilis: { label: "Kilis" },
      kirikkale: { label: "Kırıkkale" },
      kirklareli: { label: "Kırklareli" },
      kirsehir: { label: "Kırşehir" },
      kocaeli: { label: "Kocaeli" },
      konya: { label: "Konya" },
      kutahya: { label: "Kütahya" },
      malatya: { label: "Malatya" },
      manisa: { label: "Manisa" },
      mardin: { label: "Mardin" },
      mersin: { label: "Mersin" },
      mugla: { label: "Muğla" },
      mus: { label: "Muş" },
      nevsehir: { label: "Nevşehir" },
      nigde: { label: "Niğde" },
      ordu: { label: "Ordu" },
      osmaniye: { label: "Osmaniye" },
      rize: { label: "Rize" },
      sakarya: { label: "Sakarya" },
      samsun: { label: "Samsun" },
      sanliurfa: { label: "Şanlıurfa" },
      siirt: { label: "Siirt" },
      sinop: { label: "Sinop" },
      sivas: { label: "Sivas" },
      sirnak: { label: "Şırnak" },
      tekirdag: { label: "Tekirdağ" },
      tokat: { label: "Tokat" },
      trabzon: { label: "Trabzon" },
      tunceli: { label: "Tunceli" },
      usak: { label: "Uşak" },
      van: { label: "Van" },
      yalova: { label: "Yalova" },
      yozgat: { label: "Yozgat" },
      zonguldak: { label: "Zonguldak" },
    }),
    [],
  );
}
