
export const WS_CLOSE_CODE_GOINGAWAY = 1001;
export const WS_CLOSE_CODE_ABNORMAL_CLOSURE = 1006;
export const WS_CLOSE_CODE_REJECT = 1011;
export const WS_CLOSE_CODE_TRYAGAINLATER = 1013;

export const WS_MESSAGE_PING = "PING";
export const WS_MESSAGE_PONG = "PONG";
